import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import menuIcon from "../public/menu_icon.svg";
import wishlistIcon from "../public/wishlist_icon.svg";
import cartIcon from "../public/cart_icon.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="flex justify-between my-4">
            <div className="menu-icon"></div>
            <div>#Vibe Page</div>
            <div className="right-menu flex gap-2 mr-2">
              <div>
                <Image
                  src={wishlistIcon}
                  alt="wishlist"
                  width={25}
                  height={25}
                />
              </div>
              <div>
                <Image src={cartIcon} alt="wishlist" width={24} height={24} />
              </div>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
